### ISSUE TITLE
Multiple run time errors related to scipy

### ISSUE THREAD

**Issue by mxblsdl** [NREL/dgen#14]
When I run the dGen model I get the warning:
```
C:\Users\max.blasdel\Anaconda3\envs\dg3n\lib\site-packages\scipy\optimize\_minimize.py:779: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
```
I get this warning about once per second such that the console is filled repeatedly with the warning.

I was wondering:
1) Should I be concerned about this error?
2) If not, is there a way to suppress it? The helpful progress messages that are printed to the console are unusable with the constant warning message.

### Details
- Running dGen from Spyder in Anaconda environment
- Windows 10
- dGen v1.0.0

**Comment by mxblsdl** [comment]
I found there this warning is originating and a work around. Lines 641 and 658 of the `financial_functions.py` file.

I changed the function to:
```
   res_with_batt = optimize.minimize_scalar(calc_system_performance,
                                           args = (pv, utilityrate, loan, batt, system_costs, agent, rate_switch_table, False, 0),
                                           bounds = (0, max_system_kw),
                                           method = 'bounded',
                                          # tol = tol, # passing `tol` as option to avoid runtime warning
                                           options={'xatol':tol})

## Same for res_no_batt()
```
which does not raise the runtime warning. I think as long as the optimization method is bounded this should be fine. Doing some debugging on the code, the correct tolerance value was still being passed to the function.

**Comment by T-Man-Stan** [comment]
@mxblsdl Thanks for submitting this issue. The Runtimewarning is just a warning rather than an error. We've been making changes to logger statements and Runtimewarnings as part of the development work for the upcoming release of the next version of the code and will likely incorporate your change along with some other PySAM changes. Thanks for your contribution!
