### ISSUE TITLE
RuntimeWarnings

### ISSUE THREAD

**Issue by jlarc-karasj** [NREL/dgen#2]
Issue overview
--------------
During a run of the script, at the apply_state_incentives part, I hit a runtime warning. First warning is with minimize.py regarding the relative tolerance in x. The second is about an invalid value in BatteryTools.py. 

### Details
```
INFO    : ============================================
INFO    : ============================================
INFO    : Running Scenario 1 of 1
INFO    : -------------Preparing Database-------------
INFO    : Creating output schema based on diffusion_template
INFO    : 	Output schema is: diffusion_results_20200827_084832526318_v
INFO    : 	create_output_schema completed in: 0.92 seconds
INFO    : Loading Input Scenario Worksheet
INFO    : 	load_scenario completed in: 1.4 seconds
INFO    : Scenario Settings:
INFO    : 	Scenario Name: test
INFO    : 	Region: Washington
INFO    : 	Sectors: ['Residential']
INFO    : 	Technologies: ['solar']
INFO    : 	Years: 2014 - 2030
INFO    : Getting various scenario parameters
INFO    : --------------Creating Agents---------------
INFO    : 		reassign_agent_tariffs completed in: 0.01 seconds
INFO    : 	Working on 2014
INFO    : 		apply_load_growth completed in: 0.2 seconds
INFO    : 		get_state_starting_capacities completed in: 0.01 seconds
INFO    : 		calc_state_capacity_by_year completed in: 0.03 seconds
INFO    : 		filter_nem_year completed in: 0.0 seconds
INFO    : 		filter_nem_year completed in: 0.0 seconds
INFO    : 		filter_nem_year completed in: 0.0 seconds
INFO    : 		get_nem_settings completed in: 0.2 seconds
INFO    : 		apply_export_tariff_params completed in: 0.05 seconds
INFO    : 		apply_elec_price_multiplier_and_escalator completed in: 0.08 seconds
INFO    : 		apply_batt_tech_performance completed in: 0.03 seconds
INFO    : 		apply_pv_tech_performance completed in: 0.03 seconds
INFO    : 		apply_pv_prices completed in: 0.06 seconds
INFO    : 		apply_batt_prices completed in: 0.07 seconds
INFO    : 		apply_depreciation_schedule completed in: 0.03 seconds
INFO    : 		apply_carbon_intensities completed in: 0.02 seconds
INFO    : 		apply_wholesale_elec_prices completed in: 0.06 seconds
INFO    : 		apply_financial_params completed in: 0.03 seconds
INFO    : 		apply_state_incentives completed in: 0.11 seconds
			============ APPLY CHUNK ON ROW ============
C:\Users\karas_jo\.conda\envs\dg3n\lib\site-packages\scipy\optimize\_minimize.py:777: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
C:\Users\karas_jo\.conda\envs\dg3n\lib\site-packages\PySAM\BatteryTools.py:131: RuntimeWarning: invalid value encountered in double_scalars
  output_dict['time_capacity'] = batt_capacity / batt_power
WARNING : The output schema  (diffusion_results_20200827_084832526318_v) has not been deleted. Please delete manually when you are finished analyzing outputs.
INFO    : 	drop_output_schema completed in: 0.03 seconds
```

**Comment by Voltaman** [comment]
In my case, I had the following similar runtime interruption:

INFO    : ============================================
INFO    : ============================================
INFO    : Running Scenario 1 of 1
INFO    : -------------Preparing Database-------------
INFO    : Creating output schema based on diffusion_template
INFO    : 	Output schema is: diffusion_results_20241205_113455515392_fina
INFO    : 	create_output_schema completed in: 2.3 seconds
INFO    : Loading Input Scenario Worksheet
INFO    : 	load_scenario completed in: 0.92 seconds
INFO    : Scenario Settings:
INFO    : 	Scenario Name: reference
INFO    : 	Region: California
INFO    : 	Sectors: ['Commercial']
INFO    : 	Technologies: ['solar']
INFO    : 	Years: 2014 - 2050
INFO    : Getting various scenario parameters
INFO    : --------------Creating Agents---------------
INFO    : 	        reassign_agent_tariffs completed in: 0.16 seconds
INFO    : 	Working on 2014
INFO    : 		apply_load_growth completed in: 0.27 seconds
INFO    : 		get_state_starting_capacities completed in: 0.01 seconds
INFO    : 		calc_state_capacity_by_year completed in: 0.01 seconds
INFO    : 		filter_nem_year completed in: 0.0 seconds
INFO    : 		filter_nem_year completed in: 0.0 seconds
INFO    : 		filter_nem_year completed in: 0.0 seconds
INFO    : 		get_nem_settings completed in: 0.06 seconds
INFO    : 		apply_export_tariff_params completed in: 0.3 seconds
INFO    : 		apply_elec_price_multiplier_and_escalator completed in: 0.18 seconds
INFO    : 		apply_batt_tech_performance completed in: 0.14 seconds
INFO    : 		apply_pv_tech_performance completed in: 0.13 seconds
INFO    : 		apply_pv_prices completed in: 0.13 seconds
INFO    : 		apply_batt_prices completed in: 0.15 seconds
INFO    : 		apply_pv_plus_batt_prices completed in: 0.14 seconds
INFO    : 		apply_value_of_resiliency completed in: 0.15 seconds
INFO    : 		apply_depreciation_schedule completed in: 0.19 seconds
INFO    : 		apply_carbon_intensities completed in: 0.14 seconds
INFO    : 		apply_wholesale_elec_prices completed in: 0.16 seconds
INFO    : 		apply_financial_params completed in: 0.19 seconds
INFO    : 		apply_state_incentives completed in: 0.24 seconds
INFO    : Number of Workers inside chunk_on_row is 2
			============ APPLY CHUNK ON ROW ============

But in the **dgen_model.py** line 192, which has the following in it:                       **nem_state_capacity_limits.loc[nem_state_capacity_limits.state_abbr.isin(net_metering_state_df.state_abbr.loc[net_metering_state_last_year_df.pv_pctload_limit.notnull() & net_metering_state_df.pv_pctload_limit.isnull()]),'sunset_year'] = year**

I had a code analysis information which indicates:
Undefined name **net_metering_state_last_year_df**

Kindly show me how to correct this error and have the model run successfully.
