### ISSUE TITLE
pv_price_atb19_high.csv values make sense?

### ISSUE THREAD

**Issue by scepeda78** [NREL/dgen#20]
Issue overview
--------------
The investment data for this scenario pv_price_atb19_high.csv has flat prices from 2018 onwards. Does this make sense, since in an escenario a decreased should be expected, more conservative but not flat. Are the values ok?

**Comment by T-Man-Stan** [comment]
Hi @scepeda78 and thanks for your question. The 'High' scenario is equivalent to the "constant" scenario in the ATB. The 2019 ATB modeled low, mid, and constant (which is high relative to the other scenarios). 

This data can be found in the "Solar - PV Dist. Res" and "Solar - PV Dist. Comm" sheets of this excel file: https://data.nrel.gov/system/files/115/2019-ATB-data.xlsm ("2019-ATB-data.xlsm") in the NREL Data Catalog https://data.nrel.gov/submissions/115.
