### ISSUE TITLE
psycopg2.9.* no longer allows for copy_from

### ISSUE THREAD

**Issue by khettel** [NREL/dgen#25]
Issue overview
--------------
With the 2.9.* version of psycopg2 'copy_from' method fails to copy input sheet data to the agent PGAdmin input tables (i.e. input_main_scenario_options). It throws an error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/KseniyaHusak/Desktop/dgen/dgen_os/python/dgen_model.py", line 75, in main
    scenario_settings = settings.init_scenario_settings(scenario_file, model_settings, con, cur)
  File "c:\Users\KseniyaHusak\Desktop\dgen\dgen_os\python\settings.py", line 517, in init_scenario_settings
    raise Exception('\tLoading failed with the following error: {}'.format(e))
Exception:      Loading failed with the following error: relation "diffusion_results_20211102_215704509891_fina.input_main_scenari" does not exist
```
 Instead it seems copy_expert( ) needs to be used with this version. 

### Details

 - Platform (Windows 10, psycopg2- 2.9.1, python 3.8.12 )

**Comment by BT-VoteSolar** [comment]
I'd like to know how this line of code is written. I wrote:
cursor.copy_expert("COPY sql FROM S", s)

This does not work, however.
