### ISSUE TITLE
Updating state_incentives_2019 didn't impact the results

### ISSUE THREAD

**Issue by jlarc-karasj** [NREL/dgen#5]
Issue overview
--------------
The state tax incentives were updated to include various incentives within Washington state and the outputs of the model have not changed, here is the file - [state_incentives_2019.xlsx](https://github.com/NREL/dgen/files/5380005/state_incentives_2019.xlsx). The actual file is state_incentives_2019.csv, but I converted it to .xlsx to be uploaded here. The file was then imported into the psql server and we verified it was correct. Our syntax appears to align with all other production based incentives. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10 Enterprise v. 1909)
 - dGen (164641a)

**Comment by bsigrin** [comment]
Hello

Currently, though the model simulates adoption during historic years, the amount of dGen-simulated adoption is overwrriten by the actual amount of adoption. 

See: https://github.com/NREL/dgen/blob/164641ad34422dddd578ce67df2166c23c5f7c4d/dgen_os/python/diffusion_functions_elec.py#L78, lines 78- 113.

If you have not disabled/commented out this block of code that would explain the results you're seeing, i.e. all of the incentives entered in the referenced spreadsheet were during historic and not forecasted periods. Note that dGen simulates in 2-yr timesteps, where the '2018' time step represents Jan 1 2018 - Dec 30 2019.

Please comment out this code block and let us know if that impacts the results you're seeing.

**Comment by jlarc-karasj** [comment]
Hi Ben,

I had already block commented out that portion of the code after our original chat. 
![DiffusionExample](https://user-images.githubusercontent.com/58996346/96031450-35d0ab00-0e12-11eb-8268-720d5455cf80.PNG)

I also confirmed that the outputs changed after blocking out the portion of the code that backfilled known adoption.

**Comment by bsigrin** [comment]
After further investigation, unfortunately the ability to model incentives beyond the Federal ITC were not included in the Beta version of the model, i.e. the current Master branch. One of the updates of transitioning from the Alpha to Beta phase was implementing the PySAM library, i.e. using SAM to simulate project economics. The beta model does not include functionality to map incentive parameters into PySAM

See: https://github.com/NREL/dgen/blob/164641ad34422dddd578ce67df2166c23c5f7c4d/dgen_os/python/financial_functions.py#L498

However this capability will be available in the Final version (i.e. https://github.com/NREL/dgen/blob/final_release_dev/dgen_os/python/financial_functions.py#L224), which is expected to be released any day. 

Please hold off on using the final_release_dev branch as it will be incompatible with the Beta data set. THank you for your patience, if you can wait a few days for the full release that's best. Else, other options would be to implement some of the features in final_release_dev yourself, or to adjust the PV costs to calculate the effective costs after the PBI.

We will address this and close the issue once resolved.

**Comment by jlarc-karasj** [comment]
Thank you for the quick follow up! We'll hold off on any more modeling until the final release.
