### ISSUE TITLE
Issue in adding new financing terms 

### ISSUE THREAD

**Issue by ashoksekar7** [NREL/dgen#6]
Issue overview
--------------
i wanted to run a scenario with new financial assumption. After following what i think was the standard protocol to do that i got an error. 

Standard protocol: 1) I upload a new csv file in the financial terms folder and 2) input the corresponding name of the new csv file in the scenario excel file and 3) Run the model. 

When i tried to debug the issue i found that the new financial term file "financing_atb_FY19_rv" was read by the program but it contained zero rows. Upon further inspection on how the file was ingested i found that it was through the database from the diffusion_shared schema. While a file name "financing_atb_FY19_rv" was in the diffusion_shared schema there were zero rows in the table. I don't know why...  I think there was some issue in updating the diffusion_shared schema with the new file . I didn't try to solve this issue. 

Instead i added a if statement in input_data_functions.py to read the file from local folder instead of the database.

**Comment by paritoshdas** [comment]
Closed this with b378ea6
