### ISSUE TITLE
Ensure NEM does not 'snap back' for percent of peak load cases

### ISSUE THREAD

**Issue by bsigrin** [NREL/dgen#7]
Issue overview
--------------
In some cases, states with a percentage-based net metering policy it is possible for NEM settings to snap back if the state's load grows faster than the percent of DER deployment

https://github.com/NREL/dgen/blob/24cd2ba63df90529d081bb1f19e74eef869ad733/dgen_os/python/agent_mutation/elec.py#L328

Please patch, issue a pull request to @paritoshdas or @T-Man-Stan and then close this issue.

**Comment by nwillems94** [comment]
@paritoshdas @T-Man-Stan 
The plan is to fix this by configuring `elec.get_nem_settings` to modify `nem_state_capacity_limits['sunset_year']` to the current year if the NEM threshold is reached. That way, in future years, `filter_nem_year` will filter out these states. 

so `get_nem_settings` will return a modified copy of `nem_state_capacity_limits` in addition to `state_result, utility_result`

Thoughts?

**Comment by nwillems94** [comment]
@paritoshdas @T-Man-Stan 
Any progress on approving this?

**Comment by T-Man-Stan** [comment]
I thought the original plan was to just resolve it with the merge but I'll
go ahead and implement it.

Trevor

**Comment by T-Man-Stan** [comment]
Closed by the following commit: https://github.com/NREL/dgen/commit/95b71007705dd3de028b5335cec5cbb26fbf7fc5
